# Generated by Django 4.1.3 on 2022-11-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.CharField(default='some_price', max_length=40),
        ),
    ]
